### ISSUE TITLE
Getting "false" when calling getConfigFileSetting

### ISSUE THREAD

**Issue by Nautigsam** [ljsimin/MinecraftJoypadSplitscreenMod#21]
I'm working on the persistence of single-direction axis. I save the settings like this:

```java
public static void saveSingleDirectionAxis(Controller controller)
{
	List<Integer> axis = getSingleDirectionAxis(controller.getIndex());
	config.setConfigFileSetting("-SingleDirectionAxis-", controller.getName(), axisListToString(axis));
}
```

In the config file, there is this block:
```
-SingleDirectionAxis- {
    S:"Microsoft X-Box 360 pad"=3
}
```

And I try to get the setting like this:
```java
String key = "-SingleDirectionAxis-."+thisController.getName();
String axisStr = config.getConfigFileSetting(key);
```
Here, key is equal to "-SingleDirectionAxis-.Microsoft X-Box 360 pad" and axisStr is always equal to "false". Do you have any suggestion about getting a setting from config file?

**Comment by ahickey** [comment]
In configfile.java 

Try  changing this line:

		if (Minecraft.getMinecraft() != null && Minecraft.getMinecraft().getSession() != null)
		{
			userName = Minecraft.getMinecraft().getSession().getUsername();
		}

And set the userName ="myUser"; 

You'll need  something static until you finish testing.

Its probably because the config settings are different for each user.  When you start the game in the debugger you will be given a random username.  Then the settings aren't actually persisted to disk until you exit the game.  Then when you start again you are given a new username and never see it.

Perhaps that is the problem you are seeing.

**Comment by ahickey** [comment]
May be obvious but make sure the mod won't crash when this parameter isn't there (for older config files).

And if you haven't noticed the config file handling is messy and a tad confusing but works :)

**Comment by ahickey** [comment]
Nautigsam, if the following is true in linux:
Controller Name: Xbox 360 or Xbox One Joypad
OS: non Windows/Mac
Detected Axis: 6
Single direction Axis: true
Then we can default the SDA axis settings for new users like we are doing for the XBox one joypad on windows.

**Comment by ahickey** [comment]
Back to the original problem.  I remember now why I hated the config file so much.  Its very finicky.  There's a bug in the getConfigFileSetting function that overwrites strings if it tries to get it and it doesn't match a boolean.  

return config.get(category, key, false).getString();
needs to change to:
return config.get(category, key, "false").getString();

Full rewritten function here.
	public String getConfigFileSetting(String categoryKey)
	{
		int lastIndex = categoryKey.lastIndexOf('.');
		String category = categoryKey.substring(0, lastIndex);
		String key = categoryKey.substring(lastIndex + 1);
		return config.get(category, key, "false").getString();
	}
 
Wasn't noticed til now because the code using it was only putting true/false in there in the first place.  

That should get you the values you are expecting for SDA.

I thought you were using player settings but it makes more sense to have the SDA as a global type setting.

You can include this change in your update.

**Comment by Nautigsam** [comment]
That last one worked. Pull request submitted.
