### ISSUE TITLE
Flan's Mod

### ISSUE THREAD

**Issue by Nautigsam** [ljsimin/MinecraftJoypadSplitscreenMod#23]
In GameRenderHandler.java, in the UpdateInGameCamera() method, we check this boolean: lastFlansModCheckValue. What is the purpose of this value?

**Comment by ahickey** [comment]
There was some code that checks for a mod named flans mod.  This mod has its own built in handling of mouse and keyboard presses.  In order to be compatible with that popular mod we needed some special handling of when we hacked in our mouse keyboard joystick interpretation.  I was only partially able to get it to work.
On Oct 8, 2015 3:18 AM, Aurélien Bertron <notifications@github.com> wrote:In GameRenderHandler.java, in the UpdateInGameCamera() method, we check this boolean: lastFlansModCheckValue. What is the purpose of this value?
